version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: emailPay
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
volumes:
  pgdata: